### ISSUE TITLE
Auto generate entry.tp

### ISSUE THREAD

**Issue by KillerBOSS2019** [KillerBOSS2019/TouchPortal-API#9]
It would be cool for the SDK to create the entry.tp in the program just like the [TP Java sdk](https://github.com/ChristopheCVB/TouchPortalPluginSDK)

**Comment by mpaperno** [comment]
I like the idea of generating the .tp based on content/markup of the plugin script. Most attractive, I think, would be to only specify names once, in the script, vs. having to repeat all/most of the same info in the .tp.  Basics like plugin name, version, and also Settings, static States, Actions, and Events.  For example I basically have all that stuff in constants in my [plugin code](https://github.com/mpaperno/LGKeys-TouchPortal-Plugin/blob/master/src/main.py#L55) and of course repeated in the .tp.

Would that be the main feature, and/or are you thinking of other thing(s)?

Compared to the Java SDK, I think a lot of that stuff isn't necessary since Python is just so much easier to dive into (no need for subclassing and all that).  But I could see a "template" plugin Python script perhaps, with the API init calls and event listeners, and perhaps a basic `main()` to get started with.  Maybe even with some logging features or other niceties most plugins could use (but not too complicated).

**Comment by KillerBOSS2019** [comment]
Wonder if is possible to just call the Library and create a base entry.tp? like if you run `python TouchPortalAPI --darkcolor somevalue --lightcolor samevalue --name "example plugin" --id "somevalue"` might be too long i can't think of a way to create a entry.tp without being too confusing

**Comment by mpaperno** [comment]
I was thinking of a separate utility which would parse (load) a user's plugin Python code and use some standard variable names (which we define) within that script to generate the entry.tp.  For example something like

```python
TP_PLUGIN_INFO = {
  'version' : 100,
   `name` : "My Plugin"
  ... etc
}
TP_PLUGIN_SETTINGS = {
  'setting1_id` : {
    'name' : "Setting 1",
    'type' : "text",
    ... etc
  }
}
TP_PLUGIN_STATIC_STATES = { ... }
etc...
```
Which would essentially be similar to what the .tp JSON would contain anyway. But the advantage being that all that info can also be used from within the Python plugin script, so there should be no need to duplicate data, and the plugin script contains everything necessary. If anything changes in the plugin (even just version #), just generate a new entry.tp.

I'll try to come up with a quick demo/proof-of-concept and see if that makes any sense.

In any case I would vote for keeping any "sdk" functions (scripts) separate from the base API.  (Was actually going to suggest separating Tools() into it's own file.)  IMHO it is typically better to keep things as modular as possible/logical, which simplifies maintenance and gives the user more options (for example there would be no need to load all the SDK functions while actually running the plugin code/Python API, so all that would be wasted memory and a larger distribution size).

**Comment by KillerBOSS2019** [comment]
about the scripts it was my first time actually use "OOP" and make a library in python so I am not too experience

**Comment by mpaperno** [comment]
Well I think you did very well, especially for your first time!  👍🏼 

I'd like to figure out what would be useful for plugin authors... no point in building something cool but not useful.  So assuming "anything" is possible, what would be actually useful?  I'm not writing many plugins, so I'm not really sure. The only mildly annoying part for me was duplicating my names/IDs in two places and making sure they stay synced.

Maybe a good question for the Discord plugins channel? (Might be nice to have a "#plugin-authors" channel there... if there isn't one already which I can't see.)

**Comment by mpaperno** [comment]
I came up with an example/PoC of what I was talking about [above](#issuecomment-877712840).

https://github.com/mpaperno/TouchPortal-API/tree/sdk/TouchPortal-API/sdk

Basically there's an example plugin script with some variables at the top which are used to generate the `entry.tp`, using the `tpsdk-gentp.py` script.  (For lack of a better idea, I'm calling those variables "SDK definitions" for now.)  But note that they don't exactly match how the entry.tp JSON is structured.

So from the `sdk` directory just run `tpsdk-gentp.py plugin-example`  and it will generate an entry.tp (both to the console and a file in the same folder).

In the example plugin there are also some places where I used data from the "SDK definitions" vars in the plugin code itself. Which is what I meant about avoiding string duplication. And also this is why I'm indexing the "SDK definitions" entries with short unique names,, so that for example `TP_PLUGIN_ACTIONS['example']['id']`  easily gets the `id` attribute of the `example` action.

Clearly improvements are needed, and I already put some ideas down at the top of the generator script.  Any feedback is always welcome, and especially on whether something like this would even be useful at all.

**Comment by KillerBOSS2019** [comment]
Hm tried using that examples running the tpsdk-gentp.py it says `SystemExit: ERROR while trying to import plugin code from 'main': ModuleNotFoundError("No module named 'main'")`

**Comment by mpaperno** [comment]
"main.py" is just the default script name the utility tries to load.  Specify the actual script name on the command line:

`tpsdk-gentp.py plugin-example`

or

`tpsdk-gentp.py plugin-example.py`

**Comment by KillerBOSS2019** [comment]
ahhh I see
